[workspace]
authors = ["Maulik Madhavi <maulik.madhavi@gmail.com>"]
name = "ptl"
platforms = ["linux-64", "win-64"]
version = "0.1.0"
channels = ["nvidia/label/cuda-12.6.0", "nvidia", "conda-forge", "pytorch"]

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.2,<26"
gcc = ">=15.1.0,<15.2"
ipython = ">=9.4.0,<10"


[pypi-dependencies]
torch = { version = "==2.8.0+cu128", index = "https://download.pytorch.org/whl/cu128" }
tqdm = ">=4.67.1, <5"
torchvision = { version = "==0.23.0+cu128", index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { version = "==2.8.0+cu128", index = "https://download.pytorch.org/whl/cu128" }
huggingface-hub = ">=0.30.2, <0.31"
lightning = ">=2.5.3, <3"
tensorboard = ">=2.20.0, <3"
torchmetrics = ">=1.8.1, <2"
torchtext = ">=0.18.0, <0.19"
pandas = ">=2.3.2, <3"
seaborn = ">=0.13.2, <0.14"
